export const SKILL_TYPES = [
  'FIRE_ACCELERATION',
  'FIRE_EXPLOSION',
  'WATER_ACCELERATION',
  'WATER_EXPLOSION',
  'WIND_ACCELERATION',
  'WIND_EXPLOSION',
  'GHOST_SHIFT',
  'SPACE_DISTORTION',
  'STONE_HEAVY_MODE',
  'STONE_FRAGMENT_EXPLOSION',
  'LIGHTNING_ACCELERATION',
  'LIGHTNING_EXPLOSION',
  'EARTH_WALL_RUN',
  'EARTH_QUAKE',
  'ICE_GLIDE',
  'ICE_EXPLOSION',
  'DRAGON_WING_BURST',
  'DRAGON_ROAR',
  'BEAST_LEAP',
  'BEAST_CHARGE',
] as const;

export type SkillType = (typeof SKILL_TYPES)[number];
