import type { MonsterDefinition } from './monsterDefinition';

const monsterDefinitions: MonsterDefinition[] = [
  {
    id: 'fire-archetype',
    displayName: '화염 폭주',
    selectionName: '화염 폭주',
    selectionDescription: '강한 랜덤 가속과 폭발 넉백으로 한 번에 판을 뒤집는 고위험·고폭발 특성.',
    element: 'FIRE',
    stats: { massMultiplier: 1, frictionMultiplier: 1, restitutionMultiplier: 1, statusDurationMultiplier: 1 },
    skills: ['FIRE_ACCELERATION', 'FIRE_EXPLOSION'],
    tags: ['high-risk', 'burst', 'chaos'],
  },
  {
    id: 'water-archetype',
    displayName: '해류 제어',
    selectionName: '해류 제어',
    selectionDescription: '주변 상대를 느리게 만들며 흐름을 통제하는 안정적인 광역 제어 특성.',
    element: 'WATER',
    stats: { massMultiplier: 1, frictionMultiplier: 1, restitutionMultiplier: 0.9, statusDurationMultiplier: 1 },
    skills: ['WATER_ACCELERATION', 'WATER_EXPLOSION'],
    tags: ['control', 'slow'],
  },
  {
    id: 'wind-archetype',
    displayName: '폭풍 방출',
    selectionName: '폭풍 방출',
    selectionDescription: '넓은 범위의 돌풍으로 많은 상대의 위치를 한꺼번에 흔드는 광역 교란 특성.',
    element: 'WIND',
    stats: { massMultiplier: 0.9, frictionMultiplier: 1, restitutionMultiplier: 1, statusDurationMultiplier: 1 },
    skills: ['WIND_ACCELERATION', 'WIND_EXPLOSION'],
    tags: ['wide-area', 'displacement'],
  },
  {
    id: 'magic-archetype',
    displayName: '공간 왜곡',
    selectionName: '공간 왜곡',
    selectionDescription: '주변 몬스터를 예측하기 어려운 방향으로 흩뜨리는 극단적인 혼돈·변수 생성 특성.',
    element: 'MAGIC',
    stats: { massMultiplier: 0.95, frictionMultiplier: 1, restitutionMultiplier: 1, statusDurationMultiplier: 0.9 },
    skills: ['GHOST_SHIFT', 'SPACE_DISTORTION'],
    tags: ['chaos', 'random-displacement'],
  },
  {
    id: 'stone-archetype',
    displayName: '중암 충돌',
    selectionName: '중암 충돌',
    selectionDescription: '무거운 몸으로 충돌에 버티고 상대를 밀어내는 중량·몸싸움 중심 특성.',
    element: 'STONE',
    stats: { massMultiplier: 1.25, frictionMultiplier: 1, restitutionMultiplier: 0.8, statusDurationMultiplier: 1 },
    skills: ['STONE_HEAVY_MODE', 'STONE_FRAGMENT_EXPLOSION'],
    tags: ['heavy', 'collision'],
  },
  {
    id: 'lightning-archetype',
    displayName: '전격 제압',
    selectionName: '전격 제압',
    selectionDescription: '가장 강한 순간 가속과 짧은 정지 효과로 결정적인 순간을 끊는 폭발적 제압 특성.',
    element: 'LIGHTNING',
    stats: { massMultiplier: 1, frictionMultiplier: 1, restitutionMultiplier: 1, statusDurationMultiplier: 1 },
    skills: ['LIGHTNING_ACCELERATION', 'LIGHTNING_EXPLOSION'],
    tags: ['speed', 'stun'],
  },
  {
    id: 'earth-archetype',
    displayName: '대지 활주',
    selectionName: '대지 활주',
    selectionDescription: '벽과 지형을 타고 안정적으로 아래로 전진하는 지형 활용·안정 주행 특성.',
    element: 'EARTH',
    stats: { massMultiplier: 1.05, frictionMultiplier: 1.2, restitutionMultiplier: 0.8, statusDurationMultiplier: 1 },
    skills: ['EARTH_WALL_RUN', 'EARTH_QUAKE'],
    tags: ['stable', 'terrain'],
  },
  {
    id: 'ice-archetype',
    displayName: '빙결 활주',
    selectionName: '빙결 활주',
    selectionDescription: '낮은 마찰과 미끄러짐으로 속도를 오래 유지하며 상대의 제어를 무너뜨리는 관성 특성.',
    element: 'ICE',
    stats: { massMultiplier: 1, frictionMultiplier: 0.65, restitutionMultiplier: 1, statusDurationMultiplier: 1 },
    skills: ['ICE_GLIDE', 'ICE_EXPLOSION'],
    tags: ['slippery', 'momentum'],
  },
  {
    id: 'dragon-archetype',
    displayName: '용의 위압',
    selectionName: '용의 위압',
    selectionDescription: '발동 횟수는 적지만 한 번의 가속과 전방 포효가 매우 강한 고성능·저빈도 특성.',
    element: 'DRAGON',
    stats: { massMultiplier: 1.1, frictionMultiplier: 1, restitutionMultiplier: 1, statusDurationMultiplier: 0.75 },
    skills: ['DRAGON_WING_BURST', 'DRAGON_ROAR'],
    tags: ['powerful', 'low-frequency'],
  },
  {
    id: 'beast-archetype',
    displayName: '야수 본능',
    selectionName: '야수 본능',
    selectionDescription: '멈추면 본능적으로 탈출하고 가까운 상대에게 돌진하는 민첩·추적형 특성.',
    element: 'BEAST',
    stats: { massMultiplier: 0.9, frictionMultiplier: 1, restitutionMultiplier: 1, statusDurationMultiplier: 0.9 },
    skills: ['BEAST_LEAP', 'BEAST_CHARGE'],
    tags: ['agile', 'collision'],
  },
];

const registry = new Map<string, MonsterDefinition>(monsterDefinitions.map((definition) => [definition.id, definition]));

export const getMonsterDefinition = (monsterId: string) => registry.get(monsterId);
export const getAllMonsterDefinitions = () => [...registry.values()];
export const getRegisteredMonsterCount = () => registry.size;
